--- #YAML:1.0
name:                MooseX-Lists
version:             0.01
abstract:            treat arrays and hashes as lists
license:             ~
author:              
    - Dmitry Karasik <dmitry@karasik.eu.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Moose:                         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
